name: Lint ROS 2
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - main

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cpplint, flake8, lint_cmake, pep257, uncrustify, xmllint]
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: ros-tooling/setup-ros@0.6.1
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: seek_and_capture_forocoches
